// initialData.js — Données importées du fichier DEPENSES.xlsx
// 492 dépenses + 47 revenus

let _c = 0;
const id = () => "h" + (++_c);

export const initialDepenses = [
{id:id(),date:"2025-09-30",categorie:"Location pelleteuse",montant:150000,lieu:"BABAR 50",commentaire:"location peltteuse Babar 50 ",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"Achat piece",montant:1700,lieu:"Groupe électrogène ",commentaire:"3 courroies",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"Tourneurs",montant:800,lieu:"Fiesta ",commentaire:"veredou fiesta ",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"Achat piece",montant:1200,lieu:"Camion blanc 2009 Youssef",commentaire:"Tuyau d\'air camion Youssef",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"Achat piece",montant:5000,lieu:"Camion blanc 2009 Youssef",commentaire:"Tuyau d\'air et câble électrique avec prise pour camion Youssef",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"Achat piece",montant:200,lieu:"Erbil",commentaire:"Bouchon radiateur Erbil",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"Attachement",montant:70000,lieu:"Chechar 60",commentaire:"Attachement Kouti Hassan ",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"Attachement",montant:30000,lieu:"Babar 120",commentaire:"Kalguia Rabah",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"Quincaillerie",montant:600,lieu:"Retro",commentaire:"Boulons",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"GPL Fiesta",montant:225,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"Prime",montant:2000,lieu:"Rachid",commentaire:"Dépannage Chechar jusqu\'à 17h",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"Huile 7400",montant:1000,lieu:"Retro",commentaire:"15 litres huiles 15w40",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",categorie:"Reparation electricien",montant:14000,lieu:"Erbil",commentaire:"Paiement réparation erbil par moussa électricien",personne:"Nejmeddine"},
{id:id(),date:"2025-10-05",categorie:"Peinture",montant:320,lieu:"Babar 120",commentaire:"Pot de peinture blanche",personne:"Nejmeddine"},
{id:id(),date:"2025-10-05",categorie:"Quincaillerie",montant:1600,lieu:"Babar 120",commentaire:"Vachette",personne:"Nejmeddine"},
{id:id(),date:"2025-10-05",categorie:"Carburant gasoil",montant:1000,lieu:"Malaxeur Mohamed Salah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-05",categorie:"Joint spi",montant:2500,lieu:"Camion blanc 2009 Youssef",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-05",categorie:"Achat piece",montant:250,lieu:"Erbil",commentaire:"Cable accelerateur erbil",personne:"Nejmeddine"},
{id:id(),date:"2025-10-05",categorie:"Quincaillerie",montant:400,lieu:"Babar 120",commentaire:"Disque fer",personne:"Nejmeddine"},
{id:id(),date:"2025-10-05",categorie:"Transport",montant:500,lieu:"Babar 120",commentaire:"Réparation roue manitou",personne:"Nejmeddine"},
{id:id(),date:"2025-10-05",categorie:"Alimentation caisse Ramzy",montant:200000,lieu:"Ramzy",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Achat piece",montant:88800,lieu:"Camion blanc 2009 Youssef",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"GPL Fiesta",montant:215,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Prime",montant:2000,lieu:"Belkacem",commentaire:"Dépannage camion Foton jusqu\'a 21h oum le baghi",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Achat piece",montant:400,lieu:"Camion Foton",commentaire:"Boulon d\'alternateur",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Repas",montant:200,lieu:"Oum el baghi",commentaire:"Achat d\'eau et gâteau Belkacem et Youssef lors du dépannage tardif 21h",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Salaire",montant:20000,lieu:"Rachid",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Salaire",montant:30000,lieu:"Nej",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Quincaillerie",montant:100000,lieu:"Bouzidi",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"SONALGAZ",montant:9250,lieu:"Babar Garage",commentaire:"FACTURE ELECTRICITE",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Alimentation caisse Bouah",montant:5000,lieu:"Bouah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Quincaillerie",montant:90,lieu:"Camion blanc 2009 Youssef",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Quincaillerie",montant:350,lieu:"Babar 120",commentaire:"Achats Truelles",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Topographe",montant:20000,lieu:"BABAR 50",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-07",categorie:"GPL Fiesta",montant:250,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Informatique",montant:2000,lieu:"Bureau",commentaire:"Alimentation ordinateur",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Papeterie",montant:2650,lieu:"Bureau",commentaire:"feuille A4",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Papeterie",montant:200,lieu:"BABAR 50",commentaire:"Cahier de chantier",personne:"Nejmeddine"},
{id:id(),date:"2025-10-07",categorie:"Papeterie",montant:200,lieu:"Babar 120",commentaire:"Cahier de chantier",personne:"Nejmeddine"},
{id:id(),date:"2025-10-06",categorie:"Quincaillerie",montant:350,lieu:"Babar 120",commentaire:"Taloche",personne:"Nejmeddine"},
{id:id(),date:"2025-10-07",categorie:"Achat piece",montant:75000,lieu:"Derbal",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-07",categorie:"Attachement",montant:1500000,lieu:"Jalal ferrailleur",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-07",categorie:"Attachement",montant:690000,lieu:"Bouriche",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-07",categorie:"Alimentation caisse Ramzy",montant:500000,lieu:"Ramzy",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-07",categorie:"Huile 55",montant:450,lieu:"Mazda",commentaire:"Huile frein",personne:"Nejmeddine"},
{id:id(),date:"2025-10-07",categorie:"Huile 55",montant:450,lieu:"Fiesta",commentaire:"Huile frein",personne:"Nejmeddine"},
{id:id(),date:"2025-10-08",categorie:"Scanner malaxeur",montant:3500,lieu:"Malaxeur Mohamed Salah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-08",categorie:"Scanner malaxeur",montant:3500,lieu:"Malaxeur Toufik",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-08",categorie:"Soudeur",montant:750,lieu:"Soudeur",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-08",categorie:"Attachement",montant:40000,lieu:"Babar 120",commentaire:"Mkhalquia Omar",personne:"Nejmeddine"},
{id:id(),date:"2025-10-08",categorie:"Eau",montant:2000,lieu:"Babar 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-08",categorie:"Reparation pompe injection",montant:66000,lieu:"Camion blanc 2009 Youssef",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-08",categorie:"Location Manitou",montant:44000,lieu:"Urbaco",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-08",categorie:"Attachement",montant:75000,lieu:"BABAR 50",commentaire:"Location pompe béton",personne:"Nejmeddine"},
{id:id(),date:"2025-10-08",categorie:"GPL Fiesta",montant:250,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-09",categorie:"GPL Fiesta",montant:120,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-07",categorie:"Quincaillerie",montant:750,lieu:"Babar 120",commentaire:"Peinture et pinceau",personne:"Nejmeddine"},
{id:id(),date:"2025-10-08",categorie:"Reparation electricien",montant:600,lieu:"Fiesta",commentaire:"Câble jauge gpl",personne:"Nejmeddine"},
{id:id(),date:"2025-10-09",categorie:"Eau",montant:2000,lieu:"Babar 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-08",categorie:"Attachement",montant:40000,lieu:"Babar 120",commentaire:"Mkhalquia Omar",personne:"Nejmeddine"},
{id:id(),date:"2025-10-04",categorie:"Achat piece",montant:55000,lieu:"Derbal",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-14",categorie:"GPL Fiesta",montant:240,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-11",categorie:"Batteries",montant:36000,lieu:"Pelleteuse Zoui",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-11",categorie:"Huile 7400",montant:8000,lieu:"Pelleteuse Zoui",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-11",categorie:"Huile 7400",montant:130000,lieu:"Atelier",commentaire:"Achat d\'Huile pour vidanger tous les camions",personne:"Nejmeddine"},
{id:id(),date:"2025-10-11",categorie:"Attachement",montant:100000,lieu:"Chechar 220",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-11",categorie:"Reparation flexible",montant:21400,lieu:"Pelleteuse Zoui",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-12",categorie:"GPL Fiesta",montant:200,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-12",categorie:"Essence Fiesta",montant:500,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-13",categorie:"Bureau",montant:7000,lieu:"Bureau",commentaire:"Plaque d\'entreprise",personne:"Nejmeddine"},
{id:id(),date:"2025-10-13",categorie:"Achat piece",montant:7900,lieu:"Bulldozer Zoui",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-13",categorie:"Eau",montant:100,lieu:"Rachid",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Attachement",montant:60000,lieu:"Babar 120",commentaire:"Arif Walid",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Attachement",montant:27000,lieu:"Chechar 220",commentaire:"Lamri wardi",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Quincaillerie",montant:600,lieu:"Urbaco ",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Quincaillerie",montant:2700,lieu:"Malaxeur orange",commentaire:"colle et masque ",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"GPL Fiesta",montant:190,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Eau",montant:100,lieu:"Rachid",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Eau",montant:3000,lieu:"Babar 120",commentaire:"300 da la citerne d\'eau quantité 10",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Quincaillerie",montant:1800,lieu:"Urbaco",commentaire:"8 pomelles pour la porte de l\'atelier pvc",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Quincaillerie",montant:1800,lieu:"Babar 120",commentaire:"2 Gambetta Truelles 2 talloches",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Quincaillerie",montant:400,lieu:"Babar 120",commentaire:"2 gants",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Quincaillerie",montant:3480,lieu:"Babar 120",commentaire:"Tamis 2 chaussures 6 sceaux",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Attachement",montant:220,lieu:"Babar 120",commentaire:"Achat de cigarettes pour les facadiers a déduire de l\'attachement",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Reparation electricien",montant:4000,lieu:"Camion Foton",commentaire:"Électricien Moussa",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Achat piece",montant:4600,lieu:"Camion Foton",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Attachement",montant:20000,lieu:"Babar 120",commentaire:"Facadiers kabilles",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Attachement",montant:77000,lieu:"BABAR 50",commentaire:"65000 gros béton + 12000 eau",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Attachement",montant:152000,lieu:"Babar 120",commentaire:"Attachement",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Attachement",montant:150000,lieu:"Zoui",commentaire:"Attachement",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Achat piece",montant:6500,lieu:"Babar 120",commentaire:"6 couettes",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Achat piece",montant:12000,lieu:"Babar 120",commentaire:"6 matelas",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Achat piece",montant:4600,lieu:"Babar 120",commentaire:"6 draps",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Attachement",montant:54000,lieu:"Electricien",commentaire:"Vue avec Taki",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Tourneurs",montant:400,lieu:"Malaxeur orange",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Achat piece",montant:4000,lieu:"Malaxeur orange",commentaire:"Joint spi",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Sable",montant:240000,lieu:"Babar 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Platre",montant:110000,lieu:"Babar 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Mounir",montant:11980,lieu:"Chechar 60",commentaire:"Dépenses de Mounir voir factures",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Achat piece",montant:2620,lieu:"Camion Foton",commentaire:"Ampoule+ tuyau gasoil+ phare arrière",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Attachement",montant:2000,lieu:"Urbaco",commentaire:"Farid",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Lavage",montant:3500,lieu:"Howo semi",commentaire:"Lavage Camion Salah",personne:"Nejmeddine"},
{id:id(),date:"2025-10-16",categorie:"Essence Fiesta",montant:500,lieu:"Fiesta",commentaire:"Gpl et Essence Fiesta",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",categorie:"Achat piece",montant:2500,lieu:"Foton eau",commentaire:"Pompe embrayage",personne:"Nejmeddine"},
{id:id(),date:"2025-10-16",categorie:"Achat piece",montant:500,lieu:"Mazda",commentaire:"Jours tonique",personne:"Nejmeddine"},
{id:id(),date:"2025-10-15",categorie:"Attachement",montant:30000,lieu:"BABAR 50",commentaire:"Coffreur Ayachi Mostafa",personne:"Nejmeddine"},
{id:id(),date:"2025-10-20",categorie:"GPL Fiesta",montant:190,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-20",categorie:"Essence Fiesta",montant:1000,lieu:"Fiesta",commentaire:"Gpl et Essence",personne:"Nejmeddine"},
{id:id(),date:"2025-10-20",categorie:"Huile a10",montant:400,lieu:"Foton",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-20",categorie:"Prime",montant:2000,lieu:"Belkacem",commentaire:"Panne Foton du 19/10 Timgad et Kais jusqu\'à 21h30",personne:"Nejmeddine"},
{id:id(),date:"2025-10-20",categorie:"Alimentation caisse Ramzy",montant:20000,lieu:"Ramzy M.",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-20",categorie:"Reparation pompe injection",montant:58000,lieu:"Pompe injection secours",commentaire:"Khaled a fait un geste commercial il n\'a pas compté sa main d\'oeuvre (8000da)",personne:"Nejmeddine"},
{id:id(),date:"2025-10-20",categorie:"Achat piece",montant:85000,lieu:"Derbal",commentaire:"Crédit pièces",personne:"Nejmeddine"},
{id:id(),date:"2025-10-21",categorie:"Achat piece",montant:16000,lieu:"Retro",commentaire:"Rotule",personne:"Nejmeddine"},
{id:id(),date:"2025-10-21",categorie:"Achat piece",montant:4800,lieu:"Camion Foton",commentaire:"Courroies 1150/13 Et 9,5/1075",personne:"Nejmeddine"},
{id:id(),date:"2025-10-21",categorie:"Essence Fiesta",montant:1590,lieu:"Fiesta",commentaire:"290 GPL  400 huile de frein 900 liquide refroidissement",personne:"Nejmeddine"},
{id:id(),date:"2025-10-21",categorie:"Carburant gasoil",montant:4000,lieu:"Malaxeur Toufik",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-21",categorie:"Reparation electricien",montant:2000,lieu:"Camion Foton",commentaire:"Main d\'oeuvre pour le câble brûlé",personne:"Nejmeddine"},
{id:id(),date:"2025-10-21",categorie:"Quincaillerie",montant:2500,lieu:"Camion Foton",commentaire:"Cutter 150 + câble et d\'ustensiles 1500da  + bouton  500 + tuyau gasoil 350",personne:"Nejmeddine"},
{id:id(),date:"2025-10-22",categorie:"Essence Fiesta",montant:1000,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-22",categorie:"Achat piece",montant:8500,lieu:"Clarck",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-22",categorie:"Quincaillerie",montant:490,lieu:"Malaxeur orange",commentaire:"Rondelle ecrous",personne:"Nejmeddine"},
{id:id(),date:"2025-10-22",categorie:"Quincaillerie",montant:220,lieu:"Fiesta",commentaire:"Colle vase liquide refroidissement",personne:"Nejmeddine"},
{id:id(),date:"2025-10-22",categorie:"Alimentation caisse Ramzy",montant:58000,lieu:"Ramzy",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-22",categorie:"Alimentation caisse Ramzy",montant:58000,lieu:"Ramzy",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-26",categorie:"Carburant gasoil",montant:2030,lieu:"Gasoil",commentaire:"Voiture de mohamed pour aller a Setif",personne:"Nejmeddine"},
{id:id(),date:"2025-10-26",categorie:"Reparation pompe injection",montant:2900,lieu:"Camion Foton",commentaire:"Réparation injecteur",personne:"Nejmeddine"},
{id:id(),date:"2025-10-26",categorie:"Repas",montant:1700,lieu:"Nej",commentaire:"Repas mohamed et nejmeddine déplacement setif",personne:"Nejmeddine"},
{id:id(),date:"2025-10-27",categorie:"Essence Fiesta",montant:1000,lieu:"Fiesta",commentaire:"Gpl + huile et essence",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Eau",montant:3000,lieu:"Babar 120",commentaire:"10 citernes",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Quincaillerie",montant:840,lieu:"Babar 120",commentaire:"7 sceaux",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Quincaillerie",montant:1400,lieu:"Babar 120",commentaire:"10 mètres bache blanc",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Eau",montant:6000,lieu:"Babar 120",commentaire:"20 citernes",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Quincaillerie",montant:600,lieu:"Babar 120",commentaire:"20 sacs + 10 sacs boulangerie",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Quincaillerie",montant:1300,lieu:"Babar 120",commentaire:"Bâche noir",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Achat piece",montant:3600,lieu:"Peteuse JCB",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-28",categorie:"Achat piece",montant:250,lieu:"Pelleteuse JCB",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Quincaillerie",montant:1825,lieu:"Camion Foton",commentaire:"Écrous boulons",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Reparation flexible",montant:1800,lieu:"Bulldozer Zoui",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Reparation flexible",montant:15000,lieu:"Pelleteuse JCB",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-22",categorie:"Quincaillerie",montant:250,lieu:"Camion Foton",commentaire:"Cutter et colle",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Essence Fiesta",montant:1290,lieu:"Fiesta",commentaire:"Huile essence gpl",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Achat piece",montant:2500,lieu:"Pelleteuse JCB",commentaire:"Courroie",personne:"Nejmeddine"},
{id:id(),date:"2025-10-28",categorie:"Achat piece",montant:5100,lieu:"Camion Foton",commentaire:"Pièces",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Quincaillerie",montant:8000,lieu:"Zoui",commentaire:"Fil d’attache",personne:"Nejmeddine"},
{id:id(),date:"2025-10-30",categorie:"GPL Fiesta",montant:240,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-25",categorie:"Gonfleur",montant:600,lieu:"Clarck",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Quincaillerie",montant:4900,lieu:"Zoui",commentaire:"Clou + fil d’attache",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Lavage",montant:1500,lieu:"Camion bleu Amara",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Attachement",montant:5000,lieu:"Babar 120",commentaire:"Trarik Achouri",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Transport",montant:3000,lieu:"Babar 120",commentaire:"Transport de matériel",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",categorie:"Attachement",montant:50000,lieu:"BABAR 50",commentaire:"Bois AYACHI MOSTAFA",personne:"Nejmeddine"},
{id:id(),date:"2025-11-02",categorie:"Quincaillerie",montant:2850,lieu:"Babar 120",commentaire:"Pelles sceaux",personne:"Nejmeddine"},
{id:id(),date:"2025-11-02",categorie:"Quincaillerie",montant:720,lieu:"Howo nouveau",commentaire:"Boulon",personne:"Nejmeddine"},
{id:id(),date:"2025-11-02",categorie:"Achat piece",montant:13000,lieu:"Malaxeur Toufik",commentaire:"Roulement 30310koxo Joint spi 98x116x10",personne:"Nejmeddine"},
{id:id(),date:"2025-11-02",categorie:"Attachement",montant:5000,lieu:"Babar 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-02",categorie:"Prime",montant:2000,lieu:"Rachid",commentaire:"Réparation malaxeur jusqu\'à 20h",personne:"Nejmeddine"},
{id:id(),date:"2025-11-02",categorie:"Prime",montant:2000,lieu:"Belkacem",commentaire:"Réparation malaxeur jusqu\'à 20h",personne:"Nejmeddine"},
{id:id(),date:"2025-11-04",categorie:"Achat piece",montant:1000,lieu:"Clarck",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-03",categorie:"Achat piece",montant:15800,lieu:"Clarck",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-03",categorie:"Reparation electricien",montant:6500,lieu:"Camion Foton",commentaire:"Dépannage Foton",personne:"Nejmeddine"},
{id:id(),date:"2025-11-03",categorie:"Essence Fiesta",montant:760,lieu:"Fiesta",commentaire:"Gpl + essence",personne:"Nejmeddine"},
{id:id(),date:"2025-11-04",categorie:"Quincaillerie",montant:700,lieu:"Fiesta",commentaire:"2 clés",personne:"Nejmeddine"},
{id:id(),date:"2025-11-04",categorie:"Reparation electricien",montant:4000,lieu:"Camion Foton",commentaire:"Réparation camion Foton installation fil électrique",personne:"Nejmeddine"},
{id:id(),date:"2025-11-04",categorie:"Reparation electricien",montant:4000,lieu:"Clarck",commentaire:"Réparation Clark",personne:"Nejmeddine"},
{id:id(),date:"2025-11-05",categorie:"Attachement",montant:10000,lieu:"Chechar 60",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-05",categorie:"Quincaillerie",montant:10000,lieu:"Garage",commentaire:"Visseuse pour Rachid",personne:"Nejmeddine"},
{id:id(),date:"2025-11-06",categorie:"Quincaillerie",montant:1500,lieu:"Adel soudeur",commentaire:"Gant et porte baguette de soudage",personne:"Nejmeddine"},
{id:id(),date:"2025-11-06",categorie:"Essence Fiesta",montant:1085,lieu:"Atelier",commentaire:"Essence et gpl fiesta",personne:"Nejmeddine"},
{id:id(),date:"2025-11-06",categorie:"Quincaillerie",montant:480,lieu:"Howo nouveau",commentaire:"Boulon",personne:"Nejmeddine"},
{id:id(),date:"2025-10-30",categorie:"Attachement",montant:2000,lieu:"Urbaco",commentaire:"Ismael gardien",personne:"Nejmeddine"},
{id:id(),date:"2025-11-08",categorie:"Achat piece",montant:3000,lieu:"Grue 20",commentaire:"Roulement",personne:"Nejmeddine"},
{id:id(),date:"2025-11-08",categorie:"GPL Fiesta",montant:250,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-08",categorie:"Prime",montant:4000,lieu:"Rachid",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-08",categorie:"Achat piece",montant:1250,lieu:"Grue 20",commentaire:"Roulement",personne:"Nejmeddine"},
{id:id(),date:"2025-11-08",categorie:"Quincaillerie",montant:4000,lieu:"Babar 120",commentaire:"Baguettes de carrelage",personne:"Nejmeddine"},
{id:id(),date:"2025-11-08",categorie:"Achat piece",montant:10000,lieu:"Camion Lakhardar",commentaire:"Achats pièces électriques",personne:"Nejmeddine"},
{id:id(),date:"2025-11-09",categorie:"Achat piece",montant:2000,lieu:"Plateau blanc",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-24",categorie:"Achat piece",montant:3400,lieu:"Rouge 07",commentaire:"Feux croisement",personne:"Nejmeddine"},
{id:id(),date:"2025-11-24",categorie:"Achat piece",montant:1150,lieu:"Malaxeur orange",commentaire:"Boulon et écrou",personne:"Nejmeddine"},
{id:id(),date:"2025-11-24",categorie:"Achat piece",montant:3800,lieu:"Camion blanc 2009 Youssef",commentaire:"Phare stop",personne:"Nejmeddine"},
{id:id(),date:"2025-11-24",categorie:"Achat piece",montant:100000,lieu:"Derbal",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-24",categorie:"Huile usée",montant:1500,lieu:"Chechar 200",commentaire:"Huile usée",personne:"Nejmeddine"},
{id:id(),date:"2025-11-24",categorie:"Liquide de refroidissement",montant:9800,lieu:"Camion bleu Amara",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-24",categorie:"Chambre arriere",montant:28000,lieu:"Manitou",commentaire:"16.9R 24",personne:"Nejmeddine"},
{id:id(),date:"2025-11-24",categorie:"Huile 7400",montant:36250,lieu:"Camion bleu Amara",commentaire:"Huile et filtre",personne:"Nejmeddine"},
{id:id(),date:"2025-11-29",categorie:"Liquide de refroidissement",montant:6400,lieu:"Grue 25",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-29",categorie:"Huile 40",montant:3200,lieu:"Clarck",commentaire:"Vidange 8 litres clarck",personne:"Nejmeddine"},
{id:id(),date:"2025-11-27",categorie:"Achat piece",montant:350,lieu:"Bulldozer Zoui",commentaire:"Cosse",personne:"Nejmeddine"},
{id:id(),date:"2025-11-29",categorie:"Reparation electricien",montant:2000,lieu:"Camion blanc 2009 Youssef",commentaire:"Réparation antivol",personne:"Nejmeddine"},
{id:id(),date:"2025-11-29",categorie:"Reparation flexible",montant:17000,lieu:"Camion bleu Amara",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-29",categorie:"Carburant gasoil",montant:3000,lieu:"Malaxeur Toufik",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-29",categorie:"Soudeur",montant:4000,lieu:"Howo nouveau",commentaire:"Panne timimoune soudure",personne:"Nejmeddine"},
{id:id(),date:"2025-11-29",categorie:"Quincaillerie",montant:3600,lieu:"Babar 120",commentaire:"Bâche couvrir le ciment blanc",personne:"Nejmeddine"},
{id:id(),date:"2025-11-24",categorie:"Eau",montant:13000,lieu:"BABAR 50",commentaire:"Citerne pour coulage béton",personne:"Nejmeddine"},
{id:id(),date:"2025-11-24",categorie:"Beton",montant:44000,lieu:"BABAR 50",commentaire:"Adel béton",personne:"Nejmeddine"},
{id:id(),date:"2025-12-01",categorie:"Quincaillerie",montant:2000,lieu:"Babar 120",commentaire:"Tenaille disque gants",personne:"Nejmeddine"},
{id:id(),date:"2025-12-10",categorie:"Achat piece",montant:4800,lieu:"Camion Lakhardar",commentaire:"Ampoules",personne:"Nejmeddine"},
{id:id(),date:"2025-12-08",categorie:"Carburant gasoil",montant:5000,lieu:"Malaxeur Mohamed Salah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-07",categorie:"Quincaillerie",montant:4900,lieu:"Camion blanc 2011",commentaire:"Ampoules fusibles",personne:"Nejmeddine"},
{id:id(),date:"2025-12-10",categorie:"Reparation flexible",montant:6500,lieu:"Pelleteuse JCB",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-02",categorie:"Liquide de refroidissement",montant:4800,lieu:"Pelleteuse JCB",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-03",categorie:"Achat piece",montant:19250,lieu:"Malaxeur orange",commentaire:"Batteries fil électrique fusibles",personne:"Nejmeddine"},
{id:id(),date:"2025-12-07",categorie:"Achat piece",montant:3750,lieu:"Malaxeur orange",commentaire:"Goujons",personne:"Nejmeddine"},
{id:id(),date:"2025-12-13",categorie:"Quincaillerie",montant:3500,lieu:"Malaxeur orange",commentaire:"AMPOULES FUSIBLES",personne:"Nejmeddine"},
{id:id(),date:"2025-12-14",categorie:"Quincaillerie",montant:700,lieu:"Babar 120",commentaire:"DECAMETRE",personne:"Nejmeddine"},
{id:id(),date:"2025-12-14",categorie:"Quincaillerie",montant:450,lieu:"Babar 120",commentaire:"Sceaux",personne:"Nejmeddine"},
{id:id(),date:"2025-12-01",categorie:"Quincaillerie",montant:2000,lieu:"Babar 120",commentaire:"FERRAILLES / DISQUE FER / GANTS",personne:"Nejmeddine"},
{id:id(),date:"2025-12-14",categorie:"LIQUIDE DE DIRECTION",montant:1200,lieu:"Camion Foton ROUGE",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-01",categorie:"Quincaillerie",montant:3375,lieu:"Malaxeur orange",commentaire:"FIL ELECTRIQUE",personne:"Nejmeddine"},
{id:id(),date:"2025-11-30",categorie:"Quincaillerie",montant:990,lieu:"Camion bleu Amara",commentaire:"ECROUS ET BOULONS",personne:"Nejmeddine"},
{id:id(),date:"2025-12-02",categorie:"Papeterie",montant:6715,lieu:"Bureau",commentaire:"BOITE ARCHIVE RAM DE PAPIER",personne:"Nejmeddine"},
{id:id(),date:"2025-12-01",categorie:"Photocopie",montant:5650,lieu:"Chechar 200",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-14",categorie:"Achat piece",montant:57000,lieu:"Retro",commentaire:"PNEU AVANT 125/80/18",personne:"Nejmeddine"},
{id:id(),date:"2025-12-01",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-02",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-03",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-04",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-06",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-07",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-08",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-09",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-10",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-11",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-11",categorie:"Essence Fiesta",montant:1500,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-13",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-14",categorie:"Essence Fiesta",montant:290,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-18",categorie:"GPL Fiesta",montant:285,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"Quincaillerie",montant:750,lieu:"Babar 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"Achat piece",montant:2000,lieu:"Foton eau",commentaire:"COLLE",personne:"Nejmeddine"},
{id:id(),date:"2025-12-10",categorie:"Achat piece",montant:23600,lieu:"Pelteuse Zoui",commentaire:"FILTRE HUILE PELTEUSE",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"Achat piece",montant:24000,lieu:"MAZDA",commentaire:"KIT PIECE MAZDA",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"PNEUS",montant:21000,lieu:"FIESTA",commentaire:"DEUX PNEUS",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"GPL Fiesta",montant:280,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"Lavage",montant:8000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"Huile 7400",montant:14000,lieu:"Camion blanc 2011",commentaire:"22 LITRES",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"Carburant gasoil",montant:7000,lieu:"Malaxeur Mohamed Salah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"GPL Fiesta",montant:1270,lieu:"Fiesta",commentaire:"270 GPL  1000 ESSENCE CRDIT FAIT NADIR",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"Quincaillerie",montant:2000,lieu:"Foton eau",commentaire:"COLLES",personne:"Nejmeddine"},
{id:id(),date:"2025-12-19",categorie:"GPL Fiesta",montant:285,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-20",categorie:"GPL Fiesta",montant:285,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-21",categorie:"GPL Fiesta",montant:285,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"GPL Fiesta",montant:285,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"Essence Fiesta",montant:500,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Alimentation caisse Salah",montant:10000,lieu:"Salah Ouadi",commentaire:"Demande de salah 10000da",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",categorie:"Essence Fiesta",montant:500,lieu:"FIESTA",commentaire:"Essence",personne:"Nejmeddine"},
{id:id(),date:"2025-12-25",categorie:"Quincaillerie",montant:1800,lieu:"BABAR 120",commentaire:"ACHATS DE MECHE",personne:"Nejmeddine"},
{id:id(),date:"2025-12-25",categorie:"Eau",montant:1200,lieu:"BABAR 120",commentaire:"ACHATS D\'EAU CITERNE",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Batteries",montant:49000,lieu:"Howo nouveau",commentaire:"CAMION DE SALAH DEUX BATTERIES",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Batteries",montant:25000,lieu:"Foton eau",commentaire:"CAMION DE RAMADAN  DEUX BATTERIES",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Huile 40",montant:45000,lieu:"HUILE",commentaire:"CAMION DE RAMADAN  8LITRES HUILE 40",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Quincaillerie",montant:900,lieu:"LAHKDAR",commentaire:"AMPOULES",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Quincaillerie",montant:2100,lieu:"LAHKDAR",commentaire:"FLESXIBLE EAU 3 METRES",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Huile a10",montant:3000,lieu:"PELTEUSE",commentaire:"5L HUILE A10",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Pneu",montant:60000,lieu:"RETRO",commentaire:"achat d\'un pneu",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Achat piece",montant:135000,lieu:"Derbal",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"SONALGAZ",montant:180000,lieu:"Chechar 220",commentaire:"PAIEMENT DE LA FACTURE D\'ELECTRICITE",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Ferrailles",montant:84500,lieu:"BABAR 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Reparation pompe injection",montant:22000,lieu:"Foton eau",commentaire:"POMPE INJECTION FOTON EAU",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",categorie:"Alimentation caisse Salah",montant:20000,lieu:"Salah Ouadi",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"",categorie:"",montant:0,lieu:"",commentaire:"",personne:"Nej"},
{id:id(),date:"2025-12-30",categorie:"Batteries",montant:20500,lieu:"Camion blanc 2009 Youssef",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-30",categorie:"Pneu",montant:60000,lieu:"Retro",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-30",categorie:"Commande vitre",montant:6900,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-30",categorie:"Durite",montant:2400,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-30",categorie:"LIQUIDE DE DIRECTION",montant:1000,lieu:"Camion Foton ROUGE",commentaire:"Deux bouteilles",personne:"Nejmeddine"},
{id:id(),date:"2025-12-30",categorie:"Quincaillerie",montant:550,lieu:"Camion Foton ROUGE",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-30",categorie:"Transport",montant:450,lieu:"Camion Foton ROUGE",commentaire:"Toufik a pris un fraudeur pour acheter des écrous",personne:"Nejmeddine"},
{id:id(),date:"2025-12-30",categorie:"Gonfleur",montant:2000,lieu:"Camion Foton ROUGE",commentaire:"Réparation pneu",personne:"Nejmeddine"},
{id:id(),date:"2025-12-31",categorie:"SONALGAZ",montant:15650,lieu:"BABAR 50",commentaire:"BRANCHEMENT PROVISOIRE",personne:"Nejmeddine"},
{id:id(),date:"2025-12-31",categorie:"Reparation flexible",montant:5400,lieu:"Grue 25",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-31",categorie:"Reparation flexible",montant:2900,lieu:"RETRO",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-31",categorie:"Reparation flexible",montant:3300,lieu:"Camion Foton ROUGE",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-31",categorie:"GPL Fiesta",montant:290,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-31",categorie:"Essence Fiesta",montant:500,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-31",categorie:"Achat piece",montant:1000,lieu:"Camion blanc 2011",commentaire:"GOUPILLONS SERRURES",personne:"Nejmeddine"},
{id:id(),date:"2025-12-31",categorie:"Quincaillerie",montant:530,lieu:"Camion Foton ROUGE",commentaire:"Tenaille/cosse",personne:"Nejmeddine"},
{id:id(),date:"2026-01-01",categorie:"Essence",montant:500,lieu:"Babar 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-01",categorie:"Quincaillerie",montant:4300,lieu:"Adel soudeur",commentaire:"Pistolet de peinture",personne:"Nejmeddine"},
{id:id(),date:"2026-01-01",categorie:"Repas",montant:150,lieu:"Salah Ouadi",commentaire:"Petit déjeuner",personne:"Nejmeddine"},
{id:id(),date:"2026-01-01",categorie:"Alimentation caisse Salah",montant:4000,lieu:"Salah Ouadi",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-08",categorie:"Lavage",montant:3000,lieu:"Camion bleu Amara",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-08",categorie:"Lavage",montant:2500,lieu:"Camion Lakhardar",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-08",categorie:"Lavage",montant:5000,lieu:"Camion Salah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"",categorie:"Achat piece",montant:20400,lieu:"Camion blanc 2009 Youssef",commentaire:"flexible gasoil diam10 + filtre pompe direction asisitee + pompe direction assisté",personne:"Nej"},
{id:id(),date:"",categorie:"Quincaillerie",montant:950,lieu:"FIESTA",commentaire:"cles19",personne:"Nej"},
{id:id(),date:"",categorie:"Quincaillerie",montant:1100,lieu:"Camion blanc 2009 Youssef",commentaire:"ecrou + boilon 13 camion ",personne:"Nej"},
{id:id(),date:"2026-01-07",categorie:"Alimentation caisse Salah",montant:10000,lieu:"Salah Ouadi",commentaire:"Salah ma demanfe 10000 pour compléter l’Attachement zoui",personne:"Nejmeddine"},
{id:id(),date:"2026-01-07",categorie:"Prime",montant:4000,lieu:"Belkacem",commentaire:"Salah ma demande de donne 4000 a belkacem",personne:"Nejmeddine"},
{id:id(),date:"2026-01-07",categorie:"GPL Fiesta",montant:330,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-07",categorie:"Essence",montant:670,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Alimentation caisse Salah",montant:55000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Salaire",montant:20000,lieu:"Rachid",commentaire:"Complément de salaire",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Salaire",montant:30000,lieu:"Nej",commentaire:"Complément de salaire",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Attachement",montant:10000,lieu:"Chechar 200",commentaire:"Erreur de Abdelkader sur la demande il manquait 10 000 pour Fathi Lassis",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Essence Fiesta",montant:1000,lieu:"",commentaire:"700 essence + 300 gpl",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Quincaillerie",montant:800,lieu:"Camion blanc 2009 Youssef",commentaire:"Colier de serrage",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Achat piece",montant:5000,lieu:"RETRO",commentaire:"Bindisque",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Huile",montant:2000,lieu:"camion blanc 2011",commentaire:"ATF 3L + DOT 3 ",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Pneu",montant:2250,lieu:"malaxeur mohamed salah",commentaire:"reparation pneu",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"gasoil",montant:450,lieu:"malaxeur mohamed salah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Achat piece",montant:4200,lieu:"camion blanc 2011",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Achat piece",montant:2050,lieu:"camion blanc 2011",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Achat piece",montant:8400,lieu:"camion blanc 2011",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Huile",montant:9900,lieu:"FIESTA",commentaire:"VIDANGE + FILTRE CAMION EAU RAMADAN",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Achat piece",montant:2100,lieu:"camion blanc 2011",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"ACCESOIRE",montant:900,lieu:"FOTON ROUGE",commentaire:"GILET ET TRIANGLE",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Achat piece",montant:21600,lieu:"FOTON ROUGE",commentaire:"ALTERNATEUR",personne:"Nejmeddine"},
{id:id(),date:"2026-01-15",categorie:"Achat piece",montant:3000,lieu:"camion blanc 2011",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-17",categorie:"Carburant gasoil",montant:2000,lieu:"Malaxeur Toufik",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-17",categorie:"Agregats",montant:2450,lieu:"Babar 120",commentaire:"Agrégats",personne:"Nejmeddine"},
{id:id(),date:"2026-01-17",categorie:"Lavage",montant:570,lieu:"15 tones",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-18",categorie:"Achat piece",montant:3700,lieu:"Camion Foton ROUGE",commentaire:"Compresseur",personne:"Nejmeddine"},
{id:id(),date:"2026-01-18",categorie:"Achat piece",montant:2000,lieu:"Camion Foton ROUGE",commentaire:"Clapet de retour Compresseur",personne:"Nejmeddine"},
{id:id(),date:"2026-01-18",categorie:"Gpl Fiesta",montant:300,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-18",categorie:"Huile",montant:900,lieu:"Camion Foton ROUGE",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-19",categorie:"Attachement",montant:2000,lieu:"Amar Djeneh",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-19",categorie:"Reparation flexible",montant:1500,lieu:"Camion Foton ROUGE",commentaire:"Flexible de direction assistée",personne:"Nejmeddine"},
{id:id(),date:"2026-01-20",categorie:"Quincaillerie",montant:1400,lieu:"Adel soudeur",commentaire:"Ampoule + baguettes de soudeur",personne:"Nejmeddine"},
{id:id(),date:"2026-01-20",categorie:"Tourneurs",montant:1500,lieu:"malaxeur mohamed salah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-20",categorie:"Transport",montant:4000,lieu:"malaxeur mohamed salah",commentaire:"Réparation injecteurs",personne:"Nejmeddine"},
{id:id(),date:"2026-01-20",categorie:"Achat piece",montant:1800,lieu:"malaxeur mohamed salah",commentaire:"Cardan",personne:"Nejmeddine"},
{id:id(),date:"2026-01-20",categorie:"Prime",montant:4000,lieu:"Rachid",commentaire:"Dépannage foton 22h",personne:"Nejmeddine"},
{id:id(),date:"2026-01-20",categorie:"Achat piece",montant:300000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-21",categorie:"repas",montant:450,lieu:"",commentaire:"DEPLACEMENT OUMELBAGHI",personne:"Nejmeddine"},
{id:id(),date:"2026-01-25",categorie:"Achat piece",montant:4000,lieu:"Grue 25",commentaire:"Ampoules et douilles",personne:"Nejmeddine"},
{id:id(),date:"2026-01-25",categorie:"Papeterie",montant:1225,lieu:"Bureau",commentaire:"Registre spirale stylo",personne:"Nejmeddine"},
{id:id(),date:"2026-01-25",categorie:"Achat piece",montant:2000,lieu:"Grue",commentaire:"Ampoules h3",personne:"Nejmeddine"},
{id:id(),date:"2026-01-25",categorie:"ACCESOIRE",montant:2500,lieu:"camion blanc 2011",commentaire:"Extincteur",personne:"Nejmeddine"},
{id:id(),date:"2026-01-26",categorie:"Ampoules",montant:300,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-26",categorie:"Prime",montant:2000,lieu:"Rachid",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-25",categorie:"Prime",montant:2000,lieu:"Belkacem",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-26",categorie:"Reparation pompe injection",montant:26000,lieu:"malaxeur mohamed salah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-26",categorie:"Peinture",montant:1600,lieu:"malaxeur mohamed salah",commentaire:"Bombe aérosol",personne:"Nejmeddine"},
{id:id(),date:"2026-01-25",categorie:"Huile",montant:2000,lieu:"A10",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-27",categorie:"Prime",montant:2000,lieu:"Rachid",commentaire:"Panne foton sous la pluie",personne:"Nejmeddine"},
{id:id(),date:"2026-01-27",categorie:"Prime",montant:2000,lieu:"Belkacem",commentaire:"Panne camion foton sous la pluie",personne:"Nejmeddine"},
{id:id(),date:"2026-01-27",categorie:"Quincaillerie",montant:1950,lieu:"BABAR 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-27",categorie:"Huile",montant:14300,lieu:"Camion Foton ROUGE",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-27",categorie:"Peinture",montant:1900,lieu:"BABAR 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-27",categorie:"Achat piece",montant:160000,lieu:"MAZDA",commentaire:"Moteur",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Quincaillerie",montant:1050,lieu:"Mohamed  OUADI",commentaire:"Clés 16/13/10/8/7",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Quincaillerie",montant:3600,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-02",categorie:"Huile 7400",montant:21600,lieu:"Malaxeur Toufik",commentaire:"22 litres Huiles  7490 et 2 filtres huile  et 4 litres huile erbil",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Ampoules",montant:4500,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-27",categorie:"Huile 7400",montant:14300,lieu:"Camion Foton",commentaire:"22 litres huiles 7400  Filtres",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Quincaillerie",montant:1900,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Achat piece",montant:2700,lieu:"Camion Foton",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Achat piece",montant:1950,lieu:"Camion Foton",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Achat piece",montant:2100,lieu:"Camion bleu Amara",commentaire:"Feux stop",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Carburant gasoil",montant:4000,lieu:"malaxeur mohamed salah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Ampoules",montant:1200,lieu:"Camion bleu Amara",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Ampoules",montant:880,lieu:"Camion bleu Amara",commentaire:"10w",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Reparation flexible",montant:65200,lieu:"Manitou",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Reparation flexible",montant:2500,lieu:"Pelleteuse JCB",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-18",categorie:"Achat piece",montant:3700,lieu:"Camion Foton",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",categorie:"Achats pieces",montant:500,lieu:"camion blanc 2011",commentaire:"Bouton code",personne:"Nejmeddine"},
{id:id(),date:"2026-02-07",categorie:"Quincaillerie",montant:850,lieu:"Fournitures Garage",commentaire:"Collier rislan",personne:"Nejmeddine"},
{id:id(),date:"2026-02-07",categorie:"Reparation flexible",montant:34000,lieu:"Manitou  jcb",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Achat piece",montant:150,lieu:"Camion Foton ROUGE",commentaire:"Cosse et douille",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Huile",montant:21600,lieu:"Grue 25",commentaire:"Huile 5 l 7400 + huile 40 4l + filtre",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"ACCESOIRE",montant:1500,lieu:"Camion Foton",commentaire:"Clés 21 et tournevis",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Scanner",montant:2500,lieu:"FIESTA",commentaire:"Panne dérapage",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Liquide refroidissement",montant:800,lieu:"Camion blanc 2009 Youssef",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Reparation flexible",montant:1500,lieu:"Grue 25",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Carburant",montant:1250,lieu:"Mounir",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Alimentation caisse Salah",montant:22000,lieu:"Reparation betonniere",commentaire:"Kaïs",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Alimentation caisse Mohamed",montant:50000,lieu:"Chechar",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Alimentation caisse Mohamed",montant:100000,lieu:"Chechar",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Attachement",montant:35000,lieu:"Zoui",commentaire:"Demande de salah en urgence pour payer la palette de ciment",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Attachement",montant:35000,lieu:"Urbaco",commentaire:"Amar benjah",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Electricien",montant:20000,lieu:"Moussa",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"Reparation electricien",montant:6000,lieu:"Kenchela",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",categorie:"ACCESOIRE",montant:139600,lieu:"Manitou  jcb",commentaire:"Palet d\'usure",personne:"Nejmeddine"},
{id:id(),date:"2026-02-11",categorie:"ACCESOIRE",montant:500,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-11",categorie:"Carburant gasoil",montant:5000,lieu:"Manitou rouge Babar",commentaire:"SALAH",personne:"Nejmeddine"},
{id:id(),date:"2026-02-11",categorie:"Quincaillerie",montant:2500,lieu:"Babar 120",commentaire:"Clou SALAH",personne:"Nejmeddine"},
{id:id(),date:"2026-02-11",categorie:"Huile a10",montant:8000,lieu:"Pelleteuse jcb",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-12",categorie:"Batteries",montant:41600,lieu:"Malaxeur Toufik",commentaire:"2 batteries + 4 cosses",personne:"Nejmeddine"},
{id:id(),date:"2026-02-12",categorie:"Attachement",montant:33000,lieu:"Abdelkader",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-12",categorie:"Alimentation caisse Salah",montant:4000,lieu:"Salah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-13",categorie:"Carburant gasoil",montant:1000,lieu:"Grue 20",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-13",categorie:"GPL Fiesta",montant:370,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-13",categorie:"Huile a10",montant:8000,lieu:"Manitou  jcb",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-13",categorie:"Essence Fiesta",montant:575,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-14",categorie:"Huile 40",montant:450,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-14",categorie:"Quincaillerie",montant:600,lieu:"Foton eau",commentaire:"2 dégrippants",personne:"Nejmeddine"},
{id:id(),date:"2026-02-14",categorie:"Achats pieces",montant:29000,lieu:"Foton eau",commentaire:"Fusil",personne:"Nejmeddine"},
{id:id(),date:"2026-02-14",categorie:"Achats pieces",montant:21000,lieu:"Manitou  jcb",commentaire:"joints spé freins ",personne:"Nejmeddine"},
{id:id(),date:"2026-02-14",categorie:"Achats pieces",montant:17000,lieu:"Manitou  jcb",commentaire:"Pompe a graisses",personne:"Nejmeddine"},
{id:id(),date:"2026-02-15",categorie:"Batteries",montant:26950,lieu:"",commentaire:"Batteries malaxeur orange",personne:"Nejmeddine"},
{id:id(),date:"2026-02-15",categorie:"Repas",montant:1800,lieu:"",commentaire:"Ramzy",personne:"Nejmeddine"},
{id:id(),date:"2026-02-15",categorie:"Huile",montant:25000,lieu:"",commentaire:"Huiles manitou et huile pelleteuse",personne:"Nejmeddine"},
{id:id(),date:"2026-02-15",categorie:"Attachement",montant:50000,lieu:"BABAR 120",commentaire:"Kabyle façade",personne:"Nejmeddine"},
{id:id(),date:"2026-02-15",categorie:"Alimentation caisse Mohamed",montant:50000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-15",categorie:"Attachement",montant:40000,lieu:"Chechar 60",commentaire:"Plâtrier",personne:"Nejmeddine"},
{id:id(),date:"2026-02-16",categorie:"Achat piece",montant:800,lieu:"Erbil Amor",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-16",categorie:"ACCESOIRE",montant:400,lieu:"Erbil Amor",commentaire:"Huile frein",personne:"Nejmeddine"},
{id:id(),date:"2026-02-16",categorie:"Huile 5w30",montant:7500,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-17",categorie:"huile a10",montant:8260,lieu:"Manitou jcb",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-17",categorie:"ACCESOIRE",montant:3200,lieu:"15 tones",commentaire:"Durite turbo",personne:"Nejmeddine"},
{id:id(),date:"2026-02-18",categorie:"Huile a10",montant:1200,lieu:"15 tones",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-18",categorie:"Quincaillerie",montant:1100,lieu:"Babar 120",commentaire:"Disque",personne:"Nejmeddine"},
{id:id(),date:"2026-02-17",categorie:"Achat piece",montant:27500,lieu:"Malaxeur orange",commentaire:"Démarreur",personne:"Nejmeddine"},
{id:id(),date:"2026-02-17",categorie:"Ciment",montant:42000,lieu:"BABAR 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-17",categorie:"Attachement",montant:210000,lieu:"Urbaco",commentaire:"Miloud Zriad",personne:"Nejmeddine"},
{id:id(),date:"2026-02-18",categorie:"Attachement",montant:390000,lieu:"Chechar 200",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-18",categorie:"Huile 40",montant:3800,lieu:"Foton eau",commentaire:"Plus filtre",personne:"Nejmeddine"},
{id:id(),date:"2026-02-18",categorie:"Quincaillerie",montant:1700,lieu:"Ampoules",commentaire:"Plus serflex",personne:"Nejmeddine"},
{id:id(),date:"2026-02-18",categorie:"Reparation injecteurs",montant:14000,lieu:"Foton eau",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-18",categorie:"Reparation phare",montant:3000,lieu:"Camion Foton ROUGE",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-18",categorie:"Achat piece",montant:39000,lieu:"Foton eau",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-18",categorie:"Repas",montant:1500,lieu:"",commentaire:"Rachid moussa youssef Toufik nej",personne:"Nejmeddine"},
{id:id(),date:"2026-02-17",categorie:"Hourdis",montant:84000,lieu:"Chechar 200",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-18",categorie:"Electricien",montant:5000,lieu:"Moussa",commentaire:"Réparation foton rouge schacman rouge et camion de Youssef",personne:"Nejmeddine"},
{id:id(),date:"2026-02-21",categorie:"Prime",montant:2000,lieu:"Belkacem",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-22",categorie:"Essence",montant:355,lieu:"",commentaire:"Nettoyage culasse 15 tones",personne:"Nejmeddine"},
{id:id(),date:"2026-02-22",categorie:"Gpl Fiesta",montant:355,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-22",categorie:"Achat piece",montant:7500,lieu:"SHACMAN rouge",commentaire:"Joints culasse et joint d’admission",personne:"Nejmeddine"},
{id:id(),date:"2026-02-22",categorie:"Lavage",montant:2000,lieu:"SHACMAN rouge",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-22",categorie:"Huile 7400",montant:14300,lieu:"15 tones",commentaire:"22 litres",personne:"Nejmeddine"},
{id:id(),date:"2026-02-22",categorie:"Huile 7400",montant:14300,lieu:"SHACMAN rouge",commentaire:"22 litres",personne:"Nejmeddine"},
{id:id(),date:"2026-02-22",categorie:"Filtres huiles",montant:1500,lieu:"15 tones",commentaire:"2 filtres",personne:"Nejmeddine"},
{id:id(),date:"2026-02-22",categorie:"Filtres",montant:1500,lieu:"SHACMAN rouge",commentaire:"2 filtres",personne:"Nejmeddine"},
{id:id(),date:"2026-02-22",categorie:"A",montant:16500,lieu:"Quincaillerie",commentaire:"Sceau 10 kilos",personne:"Nejmeddine"},
{id:id(),date:"2026-02-25",categorie:"Graisse",montant:11500,lieu:"Magni Hafed",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-25",categorie:"Alimentation caisse Mohamed",montant:50000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-25",categorie:"Attachement",montant:20000,lieu:"BABAR 120",commentaire:"DJICHE",personne:"Nejmeddine"},
{id:id(),date:"2026-02-25",categorie:"Achat piece",montant:15000,lieu:"Tracteur",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-25",categorie:"Reparation electricien",montant:10000,lieu:"Moussa",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-03-09",categorie:"Reparation pompe injection",montant:200000,lieu:"",commentaire:"A la demande de Takiedine j\'ai donné 20 000 da a salah pour aller réparer la pompe a injection",personne:"Nejmeddine"},
{id:id(),date:"2026-03-09",categorie:"Huile",montant:30000,lieu:"Grue 25",commentaire:"Vidange et 2 deux filtres j\'ai donné l\'argent Ramzi pour quil fasse les achats",personne:"Nejmeddine"},
{id:id(),date:"2026-03-19",categorie:"Batteries",montant:24000,lieu:"15 tones",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Batteries",montant:24000,lieu:"15 tones",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Batteries",montant:16000,lieu:"Camion blanc 2009 Youssef",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Controle technique",montant:2000,lieu:"Fiesta",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Scanner",montant:1500,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Huile 90",montant:2640,lieu:"camion blanc 2011",commentaire:"5 litres",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Achat piece",montant:1100,lieu:"Camion blanc 2009 Youssef",commentaire:"4 coasses",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Achat piece",montant:2000,lieu:"Camion blanc 2009 Youssef",commentaire:"Vanne",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Reparation flexible",montant:1800,lieu:"Camion blanc 2009 Youssef",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Degrippant",montant:1000,lieu:"Camion rouge",commentaire:"Deux dégrippant",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Cles",montant:500,lieu:"Camion blanc 2009 Youssef",commentaire:"Double de clés camion Youssef",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Carburant gasoil",montant:3000,lieu:"Babar 120",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Huile",montant:11930,lieu:"Camion Foton ROUGE",commentaire:"Huile et filtre",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Quincaillerie",montant:2400,lieu:"Babar 120",commentaire:"15 teinte",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Quincaillerie",montant:4160,lieu:"BABAR 120",commentaire:"26 teintes",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Quincaillerie",montant:1900,lieu:"BABAR 120",commentaire:"Fils de fer",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Carburant + huile",montant:3000,lieu:"Grue Lakhardar",commentaire:"5 litres huile 15w40 passage technicien chinois",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Bougies",montant:2500,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Prime",montant:2000,lieu:"Belkacem",commentaire:"Salah a autorise une prime car belkacem est seul depuis 2 jours",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Vitre",montant:6500,lieu:"Camion rouge",commentaire:"Accident",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Achat piece",montant:2500,lieu:"Foton",commentaire:"Pompe embrayage",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Tourneurs",montant:6000,lieu:"Grue",commentaire:"Pièces grue",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Quincaillerie",montant:800,lieu:"Babar 120",commentaire:"Accessoires peinture",personne:"Nejmeddine"},
{id:id(),date:"2026-04-06",categorie:"Achats pieces",montant:1000,lieu:"Camion Foton ROUGE",commentaire:"Massandar",personne:"Nejmeddine"},
{id:id(),date:"2026-04-08",categorie:"Repas",montant:2350,lieu:"Repas",commentaire:"Repas rachid belkacem adel bibi et moi dépannage tebessa",personne:"Nejmeddine"},
{id:id(),date:"2026-04-08",categorie:"GPL Fiesta",montant:280,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-09",categorie:"Repas",montant:2700,lieu:"Mecanicien",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-09",categorie:"Gpl Fiesta",montant:300,lieu:"FIESTA",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-11",categorie:"Alimentation caisse Salah",montant:12000,lieu:"Salah",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-04-11",categorie:"Batteries",montant:39000,lieu:"malaxeur mohamed salah",commentaire:"Deux batteries",personne:"Nejmeddine"},
{id:id(),date:"2026-04-12",categorie:"Repas",montant:2700,lieu:"Mecanicien",commentaire:"Moussa Adel rachid belkacem et nej",personne:"Nejmeddine"},
{id:id(),date:"2026-04-12",categorie:"Achat piece",montant:0.2,lieu:"15 tones",commentaire:"Deux boutons",personne:"Nejmeddine"},
{id:id(),date:"2026-04-12",categorie:"Quincaillerie",montant:740,lieu:"SHACMAN rouge",commentaire:"Ecrou et tige filter",personne:"Nejmeddine"},
{id:id(),date:"2026-04-12",categorie:"Quincaillerie",montant:770,lieu:"15 tones",commentaire:"Baguette et écrou et boulon",personne:"Nejmeddine"},
];

export const initialRevenus = [
{id:id(),date:"2025-09-30",source:"Takieddine",montant:150000,lieu:"BABAR 50",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-02",source:"Takieddine",montant:600000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-03",source:"Nejdmeddine",montant:200000,lieu:"",commentaire:"Budget Ramzy",personne:"Ramzi"},
{id:id(),date:"2025-10-07",source:"Takieddine",montant:3000000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-07",source:"Nejemeddine",montant:500000,lieu:"Budget Caisse Ramzy",commentaire:"",personne:"Ramzi"},
{id:id(),date:"2025-10-10",source:"Takieddine",montant:100000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-11",source:"Takieddine",montant:300000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-13",source:"Takieddine",montant:160000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",source:"Takieddine",montant:360000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-18",source:"Takieddine",montant:500000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-19",source:"Takieddine",montant:200000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-25",source:"Takieddine",montant:200000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-10-29",source:"Takieddine",montant:50000,lieu:"",commentaire:"Attachement B50",personne:"Nejmeddine"},
{id:id(),date:"2025-11-03",source:"Takieddine",montant:50000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-04",source:"Takieddine",montant:70000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-11-08",source:"Attachement",montant:14000,lieu:"Babar 120",commentaire:"Bouah m’a donné l’attachement de rehali messaoud",personne:"Nejmeddine"},
{id:id(),date:"2025-11-24",source:"Takieddine",montant:255000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-10",source:"Takieddine",montant:125000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-11",source:"Takieddine",montant:160000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-15",source:"Takieddine",montant:185000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",source:"Takieddine",montant:180000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-22",source:"Takieddine",montant:86500,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-23",source:"Takieddine",montant:40000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-24",source:"Takieddine",montant:120000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2025-12-30",source:"Takiedine",montant:100000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-04",source:"Takiedine",montant:100000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-13",source:"Takiedine",montant:100000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-14",source:"Takiedine",montant:70000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-20",source:"Takiedine",montant:300000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-25",source:"Takiedine",montant:200000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-27",source:"Takiedine",montant:30000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-02",source:"Takiedine",montant:130000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-03",source:"Takiedine",montant:150000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",source:"Takiedine",montant:20000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",source:"Takiedine",montant:105000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",source:"Takiedine",montant:130000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-10",source:"Takiedine",montant:100000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-12",source:"Takiedine",montant:100000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-14",source:"Takiedine",montant:40000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-15",source:"Takiedine",montant:200000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-17",source:"Takiedine",montant:770000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-18",source:"Takiedine",montant:50000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-22",source:"Takiedine",montant:50000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-02-25",source:"Takiedine",montant:100000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-03-07",source:"Takiedine",montant:500000,lieu:"",commentaire:"Takiedine a donné l’argent directement a Mohamed au chantier",personne:"Mohamed"},
{id:id(),date:"2026-03-08",source:"Takiedine",montant:100000,lieu:"",commentaire:"",personne:"Nejmeddine"},
{id:id(),date:"2026-01-26",source:"Takiedine",montant:160000,lieu:"",commentaire:"160000 moteur mazda",personne:"Nejmeddine"},
];
